import {
  AlertTriangle,
  CheckCircle2,
  ExternalLink,
  Info,
  RefreshCw,
  XCircle,
} from 'lucide-react'
import { Badge } from '@/shared/components/ui/badge'
import { Button } from '@/shared/components/ui/button'
import { Skeleton } from '@/shared/components/ui/skeleton'
import { useNeovimStatus } from '../hooks'

interface StatusRowProps {
  label: string
  children: React.ReactNode
}

function StatusRow({ label, children }: StatusRowProps): React.JSX.Element {
  return (
    <div className="flex items-start gap-4">
      <span className="text-sm text-muted-foreground min-w-[6rem] shrink-0">
        {label}
      </span>
      <div className="text-sm">{children}</div>
    </div>
  )
}

export function NeovimStatus(): React.JSX.Element {
  const { state, refresh, isDetecting, result } = useNeovimStatus()

  // Loading state
  if (state.status === 'idle' || state.status === 'detecting') {
    return <NeovimStatusSkeleton />
  }

  // Error state
  if (state.status === 'error') {
    return (
      <div className="space-y-4">
        <div className="flex items-center gap-2 text-destructive">
          <XCircle className="h-4 w-4" />
          <span className="text-sm font-medium">Detection failed</span>
        </div>
        <p className="text-sm text-muted-foreground">{state.error}</p>
        <Button
          variant="outline"
          size="sm"
          onClick={() => void refresh()}
          disabled={isDetecting}
        >
          <RefreshCw
            className={`h-4 w-4 mr-2 ${isDetecting ? 'animate-spin' : ''}`}
          />
          Try Again
        </Button>
      </div>
    )
  }

  // Memory mode
  if (result?.found === false && result.errorCode === 'memory-mode') {
    return (
      <div className="space-y-3">
        <div className="flex items-center gap-2 text-muted-foreground">
          <AlertTriangle className="h-4 w-4" />
          <span className="text-sm">Not available in browser mode</span>
        </div>
        <p className="text-sm text-muted-foreground">
          Neovim detection requires the desktop app. Run the app with Tauri to
          enable this feature.
        </p>
      </div>
    )
  }

  // Not found
  if (result?.found === false) {
    return (
      <div className="space-y-4">
        <StatusRow label="Status">
          <div className="flex items-center gap-2">
            <XCircle className="h-4 w-4 text-destructive" />
            <span className="font-medium">Not found</span>
          </div>
        </StatusRow>

        <div className="rounded-lg border border-dashed p-4 space-y-2">
          <p className="text-sm text-muted-foreground">
            Neovim is not installed or not in your PATH.
          </p>
          <a
            href="https://neovim.io"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-sm text-primary hover:underline"
          >
            Install Neovim
            <ExternalLink className="h-3 w-3" />
          </a>
        </div>

        <Button
          variant="outline"
          size="sm"
          onClick={() => void refresh()}
          disabled={isDetecting}
        >
          <RefreshCw
            className={`h-4 w-4 mr-2 ${isDetecting ? 'animate-spin' : ''}`}
          />
          Detect Again
        </Button>
      </div>
    )
  }

  // Found - narrow the type
  if (!result || !result.found) {
    return <NeovimStatusSkeleton />
  }

  return (
    <div className="space-y-4">
      <div className="space-y-3">
        <StatusRow label="Status">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-green-500" />
            <span className="font-medium">Found</span>
            <Badge variant="secondary" className="text-xs">
              v{result.version}
            </Badge>
          </div>
        </StatusRow>

        <StatusRow label="Binary">
          <code className="text-xs bg-muted px-1.5 py-0.5 rounded">
            {result.binaryPath}
          </code>
        </StatusRow>

        <StatusRow label="Config">
          <code className="text-xs bg-muted px-1.5 py-0.5 rounded">
            {result.configPath}
          </code>
        </StatusRow>

        <StatusRow label="Status">
          {result.hasExistingConfig ? (
            result.isOurConfig ? (
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-green-500" />
                <span>Generated by vinela</span>
              </div>
            ) : (
              <div className="flex items-center gap-2">
                <Info className="h-4 w-4 text-blue-500" />
                <span>Existing config found</span>
              </div>
            )
          ) : (
            <span className="text-muted-foreground">No config file</span>
          )}
        </StatusRow>
      </div>

      <Button
        variant="outline"
        size="sm"
        onClick={() => void refresh()}
        disabled={isDetecting}
      >
        <RefreshCw
          className={`h-4 w-4 mr-2 ${isDetecting ? 'animate-spin' : ''}`}
        />
        Refresh
      </Button>
    </div>
  )
}

function NeovimStatusSkeleton(): React.JSX.Element {
  return (
    <div className="space-y-3">
      <div className="flex items-center gap-4">
        <Skeleton className="h-4 w-16" />
        <Skeleton className="h-4 w-32" />
      </div>
      <div className="flex items-center gap-4">
        <Skeleton className="h-4 w-16" />
        <Skeleton className="h-4 w-48" />
      </div>
      <div className="flex items-center gap-4">
        <Skeleton className="h-4 w-16" />
        <Skeleton className="h-4 w-40" />
      </div>
    </div>
  )
}
