import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { DeployRequest, DeployResult } from '../../types'

// Mock storage module
const mockIsMemoryMode = vi.fn()
vi.mock('@/shared/lib/storage', () => ({
  isMemoryMode: () => mockIsMemoryMode(),
}))

// Mock direct-fs (replaces scoped-fs for all deploy I/O)
const mockDeployToPath = vi.fn()
const mockReadTextFileDirect = vi.fn()
const mockPathExistsDirect = vi.fn()
const mockFileUidDirect = vi.fn()
vi.mock('@/shared/lib/direct-fs', () => ({
  deployToPath: (...args: unknown[]) => mockDeployToPath(...args),
  readTextFileDirect: (...args: unknown[]) => mockReadTextFileDirect(...args),
  pathExistsDirect: (...args: unknown[]) => mockPathExistsDirect(...args),
  fileUidDirect: (...args: unknown[]) => mockFileUidDirect(...args),
}))

// Mock tauri api/path (used by path-resolution.ts::expandPath)
vi.mock('@tauri-apps/api/path', () => ({
  homeDir: vi.fn().mockResolvedValue('/home/user'),
}))

// Mock neovim module
const mockCreateBackup = vi.fn()
const mockDetectNeovim = vi.fn()
vi.mock('@/features/neovim', () => ({
  createBackup: (...args: unknown[]) => mockCreateBackup(...args),
  detectNeovim: (...args: unknown[]) => mockDetectNeovim(...args),
  GENERATED_CONFIG_MARKER: '-- Generated by vinela',
}))

// Mock settings module
const mockLoadAppSettings = vi.fn()
const mockGetEffectiveOutputPath = vi.fn()
vi.mock('@/shared/lib/settings', () => ({
  loadAppSettings: () => mockLoadAppSettings(),
  getEffectiveOutputPath: (settings: unknown) =>
    mockGetEffectiveOutputPath(settings),
  getBackupFolderPath: vi.fn(),
}))

describe('deploy', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    // Default: path does not exist, deploy succeeds, read-back succeeds
    mockPathExistsDirect.mockResolvedValue(false)
    mockDeployToPath.mockResolvedValue(42)
    mockReadTextFileDirect.mockResolvedValue(
      '-- Generated by vinela\n-- content',
    )
    mockFileUidDirect.mockResolvedValue(1000)
  })

  describe('memory mode guard', () => {
    it('returns error when in memory mode', async () => {
      mockIsMemoryMode.mockReturnValue(true)

      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: '-- test',
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('memory-mode')
        expect(result.error).toContain('browser mode')
      }
    })
  })

  describe('path resolution', () => {
    beforeEach(() => {
      mockIsMemoryMode.mockReturnValue(false)
      mockLoadAppSettings.mockResolvedValue({
        theme: 'system',
        recentProjects: [],
      })
      mockGetEffectiveOutputPath.mockReturnValue('~/.config/nvim/init.lua')
    })

    it('resolves path and creates parent directory via deployToPath', async () => {
      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- test content`,
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.outputPath).toBe('/home/user/.config/nvim/init.lua')
        // deployToPath is called with parentDir and outputPath
        expect(mockDeployToPath).toHaveBeenCalledWith(
          '/home/user/.config/nvim',
          '/home/user/.config/nvim/init.lua',
          expect.any(String),
        )
      }
    })
  })

  describe('existing config handling', () => {
    beforeEach(() => {
      mockIsMemoryMode.mockReturnValue(false)
      mockLoadAppSettings.mockResolvedValue({
        theme: 'system',
        recentProjects: [],
      })
      mockGetEffectiveOutputPath.mockReturnValue('~/.config/nvim/init.lua')
    })

    it('writes directly when no existing config', async () => {
      mockPathExistsDirect.mockResolvedValue(false)

      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- test`,
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(mockCreateBackup).not.toHaveBeenCalled()
      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.backupCreated).toBe(false)
      }
    })

    it('creates backup for existing non-generated config', async () => {
      // File exists
      mockPathExistsDirect.mockResolvedValue(true)
      // Content is NOT our generated config (no marker)
      const existingContent = '-- User config\nprint("hello")'
      mockReadTextFileDirect.mockResolvedValue(existingContent)
      mockCreateBackup.mockResolvedValue({
        success: true,
        backup: {
          id: 'test-backup',
          backupPath: '/backups/init.lua.backup.bak',
          sourcePath: '/home/user/.config/nvim/init.lua',
          createdAt: new Date().toISOString(),
          neovimVersion: '0.10.0',
          sizeBytes: 100,
        },
      })
      mockDetectNeovim.mockResolvedValue({
        found: true,
        binaryPath: '/usr/bin/nvim',
        version: '0.10.0',
        versionDisplay: 'NVIM v0.10.0',
        configPath: '/home/user/.config/nvim/init.lua',
        hasExistingConfig: true,
        isOurConfig: false,
      })

      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(mockCreateBackup).toHaveBeenCalledWith(
        '/home/user/.config/nvim/init.lua',
        '0.10.0',
        true,
      )
      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.backupCreated).toBe(true)
        expect(result.backupPath).toBe('/backups/init.lua.backup.bak')
      }
    })

    it('skips backup for our generated config', async () => {
      // File exists
      mockPathExistsDirect.mockResolvedValue(true)
      // Content IS our generated config (has marker)
      const existingContent = `-- Generated by vinela\n-- generated code`
      mockReadTextFileDirect.mockResolvedValue(existingContent)
      // UIDs match (same owner)
      mockFileUidDirect.mockResolvedValue(1000)

      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- new generated code`,
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(mockCreateBackup).not.toHaveBeenCalled()
      expect(result.success).toBe(true)
      if (result.success) {
        expect(result.backupCreated).toBe(false)
      }
    })
  })

  describe('backup failure handling', () => {
    beforeEach(() => {
      mockIsMemoryMode.mockReturnValue(false)
      mockLoadAppSettings.mockResolvedValue({
        theme: 'system',
        recentProjects: [],
      })
      mockGetEffectiveOutputPath.mockReturnValue('~/.config/nvim/init.lua')
    })

    it('aborts deploy when backup fails', async () => {
      // File exists with non-generated content
      mockPathExistsDirect.mockResolvedValue(true)
      const existingContent = '-- User config'
      mockReadTextFileDirect.mockResolvedValue(existingContent)
      mockCreateBackup.mockResolvedValue({
        success: false,
        error: 'Disk full',
      })
      mockDetectNeovim.mockResolvedValue({
        found: true,
        binaryPath: '/usr/bin/nvim',
        version: '0.10.0',
        versionDisplay: 'NVIM v0.10.0',
        configPath: '/home/user/.config/nvim/init.lua',
        hasExistingConfig: true,
        isOurConfig: false,
      })

      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('backup-failed')
        expect(result.error).toContain('backup')
      }
      expect(mockDeployToPath).not.toHaveBeenCalled()
    })
  })

  describe('write failure handling', () => {
    beforeEach(() => {
      mockIsMemoryMode.mockReturnValue(false)
      mockLoadAppSettings.mockResolvedValue({
        theme: 'system',
        recentProjects: [],
      })
      mockGetEffectiveOutputPath.mockReturnValue('~/.config/nvim/init.lua')
      // No existing file for these tests
      mockPathExistsDirect.mockResolvedValue(false)
    })

    it('returns permission-denied error', async () => {
      mockDeployToPath.mockRejectedValue(
        new Error('Failed to write: EACCES: permission denied'),
      )

      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('permission-denied')
      }
    })

    it('returns write-failed error for other errors', async () => {
      mockDeployToPath.mockRejectedValue(new Error('Disk full'))

      const { deployGeneratedConfig } = await import('../deploy')

      const request: DeployRequest = {
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      }

      const result: DeployResult = await deployGeneratedConfig(request)

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('write-failed')
      }
    })
  })

  describe('directory creation failure handling', () => {
    beforeEach(() => {
      mockIsMemoryMode.mockReturnValue(false)
      mockLoadAppSettings.mockResolvedValue({
        theme: 'system',
        recentProjects: [],
      })
      mockGetEffectiveOutputPath.mockReturnValue('~/.config/nvim/init.lua')
      mockPathExistsDirect.mockResolvedValue(false)
    })

    it('returns directory-creation-failed for Rust parent-creation prefix', async () => {
      mockDeployToPath.mockRejectedValue(
        new Error(
          'Failed to create parent directory "/home/user/.config/nvim": Not a directory',
        ),
      )

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('directory-creation-failed')
        expect(result.error).toContain('/home/user/.config/nvim/init.lua')
      }
    })

    it('returns directory-creation-failed for outside-home directory symlink detail', async () => {
      const blockerDetail =
        'path component "/home/user/.config/escape" is a symbolic link whose target "/tmp/outside" is not under the home directory'
      mockDeployToPath.mockRejectedValue(
        new Error(
          `Failed to create parent directory "/home/user/.config/nvim": ${blockerDetail}`,
        ),
      )

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('directory-creation-failed')
        expect(result.error).toContain('/home/user/.config/nvim/init.lua')
        expect(result.error).toContain(blockerDetail)
      }
    })

    it('returns write-failed for output-file symlink backend rejection', async () => {
      mockDeployToPath.mockRejectedValue(
        new Error(
          'Failed to write "/home/user/.config/nvim/init.lua": Vinela will not write through output-file symlinks at "/home/user/.config/nvim/init.lua"; configure the real ordinary file path or repair the link manually',
        ),
      )

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('write-failed')
        expect(result.error).toContain('output-file symlinks')
        expect(result.error).not.toContain('Failed to create parent directory')
      }
    })

    it('returns directory-creation-failed for non-directory blocker detail', async () => {
      const blockerDetail =
        'path component "/home/user/.config/nvim" exists but is not a directory'
      mockDeployToPath.mockRejectedValue(
        new Error(
          `Failed to create parent directory "/home/user/.config/nvim": ${blockerDetail}`,
        ),
      )

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('directory-creation-failed')
        expect(result.error).toContain('/home/user/.config/nvim/init.lua')
        expect(result.error).toContain(blockerDetail)
      }
    })

    it('returns directory-creation-failed for unresolved backend EEXIST shape', async () => {
      // Error-contract coverage only: unresolved backend AlreadyExists must not
      // become deploy success; Rust postcondition handling is tested in lib.rs.
      mockDeployToPath.mockRejectedValue(
        new Error(
          'Failed to create parent directory "/home/user/.config/nvim": File exists (os error 17)',
        ),
      )

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('directory-creation-failed')
        expect(result.error).toContain('/home/user/.config/nvim/init.lua')
        expect(result.error).toContain('File exists (os error 17)')
      }
    })

    it('preserves raw string parent-creation errors', async () => {
      mockDeployToPath.mockRejectedValue(
        'Failed to create parent directory "/home/user/.config/nvim": permission denied',
      )

      const { deployGeneratedConfig } = await import('../deploy')
      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('directory-creation-failed')
        expect(result.error).toContain('permission denied')
      }
    })

    it('returns permission-denied for mkdir permission errors', async () => {
      mockDeployToPath.mockRejectedValue(
        new Error('Failed to create directory: os error 13: Permission denied'),
      )

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('permission-denied')
        expect(result.error).toContain('Permission denied')
      }
    })

    it('preserves unrelated raw string errors as write-failed', async () => {
      mockDeployToPath.mockRejectedValue('scope violation')

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('write-failed')
        expect(result.error).toContain('scope violation')
      }
    })

    it('uses unknown fallback for non-string non-Error rejection', async () => {
      mockDeployToPath.mockRejectedValue(null)

      const { deployGeneratedConfig } = await import('../deploy')

      const result: DeployResult = await deployGeneratedConfig({
        projectId: 'test-project',
        projectPath: '/test/project',
        initLua: `-- Generated by vinela\n-- generated`,
      })

      expect(result.success).toBe(false)
      if (!result.success) {
        expect(result.errorCode).toBe('write-failed')
        expect(result.error).toContain('Unknown write error')
      }
    })
  })
})
