export { GENERATED_CONFIG_MARKER } from '@/shared/lib/app-identity'

// ============================================
// Neovim Detection Types
// ============================================

/**
 * Result of Neovim detection.
 * Discriminated union: check `found` to narrow the type.
 */
export type NeovimDetectionResult =
  | {
      found: true
      /** Absolute path to nvim binary (e.g., "/usr/bin/nvim") */
      binaryPath: string
      /** Parsed version string (e.g., "0.10.2") */
      version: string
      /** Full version output for display (e.g., "NVIM v0.10.2") */
      versionDisplay: string
      /** Absolute path to config file (e.g., "/home/user/.config/nvim/init.lua") */
      configPath: string
      /** Whether init.lua exists at configPath */
      hasExistingConfig: boolean
      /** Whether existing init.lua was generated by vinela */
      isOurConfig: boolean
    }
  | {
      found: false
      /** Human-readable error message */
      error: string
      /** Error code for programmatic handling */
      errorCode: NeovimDetectionErrorCode
    }

/**
 * Error codes for detection failures.
 */
export type NeovimDetectionErrorCode =
  | 'not-in-path' // nvim command not found
  | 'execution-failed' // nvim --version failed
  | 'parse-failed' // Could not parse version output
  | 'memory-mode' // Running in browser mode

// ============================================
// Backup Types
// ============================================

/**
 * Metadata for a single backup.
 */
export interface BackupInfo {
  /** Unique backup ID (derived from timestamp) */
  id: string
  /** Full path to backup file in AppData/backups/ */
  backupPath: string
  /** Original source path that was backed up */
  sourcePath: string
  /** ISO timestamp when backup was created */
  createdAt: string
  /** Neovim version at time of backup (for reference) */
  neovimVersion: string
  /** File size in bytes */
  sizeBytes: number
}

/**
 * Metadata stored alongside each backup file.
 * Filename: {backup-name}.meta.json
 */
export interface BackupMetadata {
  sourcePath: string
  createdAt: string
  neovimVersion: string
  sizeBytes: number
}

/**
 * Result of backup creation.
 * Discriminated union for clear success/skip/failure states.
 */
export type BackupResult =
  | { success: true; backup: BackupInfo }
  | { success: true; skipped: true; reason: SkipReason }
  | { success: false; error: string }

/**
 * Reasons why a backup might be skipped.
 */
export type SkipReason =
  | 'our-config' // Config has our marker, no need to backup
  | 'no-existing-config' // No config file exists
  | 'memory-mode' // Running in browser mode

export type RestoreResult =
  | { success: true }
  | { success: false; error: string }

export type ListBackupsResult =
  | { success: true; backups: BackupInfo[] }
  | { success: false; error: string }

export type DeleteBackupResult =
  | { success: true }
  | { success: false; error: string }

// ============================================
// Hook State Types
// ============================================

/**
 * State for useNeovimStatus hook.
 */
export type NeovimStatusState =
  | { status: 'idle' }
  | { status: 'detecting' }
  | { status: 'detected'; result: NeovimDetectionResult }
  | { status: 'error'; error: string }

/**
 * State for useBackups hook.
 */
export type BackupsState =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'loaded'; backups: BackupInfo[] }
  | { status: 'error'; error: string }

// ============================================
// Constants
// ============================================

/** Maximum number of backups to retain */
export const MAX_BACKUPS = 5

/** Backup file extension */
export const BACKUP_EXTENSION = '.bak'

/** Backup metadata file extension */
export const BACKUP_META_EXTENSION = '.meta.json'
