// ============================================
// Tests for Lua Block Balance Checker (Gap 6)
// ============================================

import { describe, expect, it } from 'vitest'
import {
  type BlockBalanceResult,
  checkLuaBlockBalance,
} from '../lua-block-balance'

describe('checkLuaBlockBalance', () => {
  // ============================================
  // Balanced cases
  // ============================================

  it('returns balanced for empty string', () => {
    const result = checkLuaBlockBalance('')
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(0)
    expect(result.closers).toBe(0)
  })

  it('returns balanced for simple function with end', () => {
    const lua = ['local function greet()', '  print("hello")', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('returns balanced for if/end', () => {
    const lua = ['if condition then', '  doSomething()', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('returns balanced for if/else/end (else is transparent)', () => {
    const lua = ['if condition then', '  doA()', 'else', '  doB()', 'end'].join(
      '\n',
    )
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('returns balanced for if/elseif/end (elseif is transparent)', () => {
    const lua = [
      'if x == 1 then',
      '  doA()',
      'elseif x == 2 then',
      '  doB()',
      'else',
      '  doC()',
      'end',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('returns balanced for numeric for loop (for counts as 1 opener, end is 1 closer)', () => {
    // In Lua: `for ... do ... end` — `for` is the opener, `end` is the closer.
    // `do` is part of the loop header syntax and is excluded from counting.
    const lua = ['for i = 1, 10 do', '  print(i)', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1) // 'for' only — 'do' is excluded
    expect(result.closers).toBe(1) // 'end'
  })

  it('returns balanced for generic for loop', () => {
    const lua = ['for k, v in pairs(t) do', '  print(k, v)', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('returns balanced for while loop', () => {
    const lua = ['while running do', '  step()', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1) // 'while' only — 'do' is excluded
    expect(result.closers).toBe(1) // 'end'
  })

  it('returns balanced for repeat/until', () => {
    const lua = ['repeat', '  step()', 'until done'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1) // 'repeat'
    expect(result.closers).toBe(1) // 'until'
  })

  it('returns balanced for nested functions', () => {
    const lua = [
      'function outer()',
      '  function inner()',
      '    return 42',
      '  end',
      'end',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(2)
    expect(result.closers).toBe(2)
  })

  it('returns balanced for anonymous function in variable', () => {
    const lua = ['local f = function()', '  return 1', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('returns balanced for realistic generated init.lua', () => {
    // Simulates a realistic init.lua output with multiple block types
    const lua = [
      '-- Generated by vinela',
      '-- Project: My Config',
      '',
      'vim.opt.number = true',
      '',
      'local function setup_telescope()',
      "  require('telescope').setup({})",
      'end',
      '',
      "vim.keymap.set('n', '<leader>ff', function()",
      "  require('telescope.builtin').find_files()",
      'end)',
      '',
      "if vim.fn.has('nvim-0.9') == 1 then",
      '  setup_telescope()',
      'end',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
  })

  it('returns balanced for a mix of all opener types', () => {
    const lua = [
      'function setup()',
      '  if condition then',
      '    for i = 1, 5 do',
      '      print(i)',
      '    end',
      '  end',
      '  while running do',
      '    step()',
      '  end',
      '  repeat',
      '    tick()',
      '  until done',
      'end',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    // function(1) + if(1) + for(1) + while(1) + repeat(1) = 5 openers
    expect(result.openers).toBe(5)
    // end(4) + until(1) = 5 closers
    expect(result.closers).toBe(5)
  })

  it('ignores keywords inside a generated long-bracket code block', () => {
    const lua = [
      'local function _code_block_tabline()',
      '  vim.cmd [[',
      '    function MyTabLine()',
      '      for i in range(tabpagenr("$"))',
      '        if i == 1',
      '        endif',
      '      endfor',
      '    endfunction',
      '  ]]',
      'end',
      '_code_block_tabline()',
    ].join('\n')

    expect(checkLuaBlockBalance(lua)).toEqual({
      balanced: true,
      openers: 1,
      closers: 1,
    })
  })

  it('ignores levelled long-bracket literals', () => {
    expect(
      checkLuaBlockBalance(
        'vim.cmd [=[function if for while repeat do end until]=]',
      ),
    ).toEqual({ balanced: true, openers: 0, closers: 0 })
  })

  it.each<[string, BlockBalanceResult]>([
    [
      'local marker = "[["\nif ready then\n]]',
      { balanced: false, openers: 1, closers: 0 },
    ],
    [
      '-- [[ marker\nif ready then\n]]',
      { balanced: false, openers: 1, closers: 0 },
    ],
    ['--[=[x]=] if ready then', { balanced: false, openers: 1, closers: 0 }],
  ])('does not hide executable blocks after opener-shaped text', (lua, expected) => {
    expect(checkLuaBlockBalance(lua)).toEqual(expected)
  })

  // ============================================
  // Imbalanced cases (generator bugs)
  // ============================================

  it('detects unclosed if block (more openers than closers)', () => {
    const lua = [
      'if condition then',
      '  doSomething()',
      '-- generator forgot to emit end',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(false)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(0)
  })

  it('detects extra end (more closers than openers)', () => {
    const lua = ['vim.opt.number = true', 'end', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(false)
    expect(result.openers).toBe(0)
    expect(result.closers).toBe(2)
  })

  it('detects unclosed function block', () => {
    const lua = [
      'function mySetup()',
      '  vim.opt.number = true',
      '-- generator forgot to emit end',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(false)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(0)
  })

  it('detects two unclosed blocks', () => {
    const lua = [
      'function outer()',
      '  if cond then',
      '    doSomething()',
      '  -- both end statements missing',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(false)
    expect(result.openers).toBe(2)
    expect(result.closers).toBe(0)
  })

  // ============================================
  // Comment-stripping behaviour
  // ============================================

  it('ignores block keywords inside line comments', () => {
    // All keywords appear only in comments — result should be balanced (0/0)
    const lua = [
      '-- if condition then',
      '-- function foo()',
      '-- for i = 1, 10 do',
      '-- while running do',
      '-- repeat',
      '-- end',
      '-- end',
      '-- end',
      '-- end',
      '-- until done',
      'vim.opt.number = true',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(0)
    expect(result.closers).toBe(0)
  })

  it('counts keywords that appear before -- on the same line', () => {
    // 'function' appears before the comment; 'end' appears before the comment
    const lua = [
      'function foo() -- this opens a function block',
      '  return 1',
      'end -- this closes it',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  // ============================================
  // String-stripping behaviour
  // ============================================

  it('ignores block keywords inside double-quoted strings', () => {
    const lua = [
      'local msg = "if this were real then end"',
      'vim.notify(msg)',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(0)
    expect(result.closers).toBe(0)
  })

  it('ignores block keywords inside single-quoted strings', () => {
    const lua = [
      "local cmd = 'for i = 1, 10 do print(i) end'",
      'vim.cmd(cmd)',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(0)
    expect(result.closers).toBe(0)
  })

  it('handles escaped quotes inside double-quoted strings', () => {
    const lua = 'local s = "he said \\"if true then end\\""'
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(0)
    expect(result.closers).toBe(0)
  })

  it('does not treat -- inside a string as a comment (false-positive regression)', () => {
    // `print('a--b')` contains `--` inside a string literal.
    // Stripping comments BEFORE strings would truncate the line at `--b')`
    // and drop the real `end` token, producing a false imbalance.
    const lua = ['function setup()', "  print('a--b')", 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('does not treat -- inside a double-quoted string as a comment', () => {
    const lua = ['function setup()', '  vim.cmd("--flag")', 'end'].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  it('counts real keywords outside strings even when strings contain keywords', () => {
    const lua = [
      'local msg = "if this were real then end"',
      'if true then',
      '  vim.notify(msg)',
      'end',
    ].join('\n')
    const result = checkLuaBlockBalance(lua)
    expect(result.balanced).toBe(true)
    expect(result.openers).toBe(1)
    expect(result.closers).toBe(1)
  })

  // ============================================
  // Return type shape
  // ============================================

  it('returns a BlockBalanceResult with all three fields', () => {
    const result: BlockBalanceResult = checkLuaBlockBalance('')
    expect(result).toHaveProperty('balanced')
    expect(result).toHaveProperty('openers')
    expect(result).toHaveProperty('closers')
  })

  it('balanced is true iff openers === closers', () => {
    // openers > closers
    const r1 = checkLuaBlockBalance('function foo()')
    expect(r1.balanced).toBe(r1.openers === r1.closers)

    // openers === closers
    const r2 = checkLuaBlockBalance('function foo() end')
    expect(r2.balanced).toBe(true)
    expect(r2.openers).toBe(r2.closers)
  })
})
