import { describe, expect, it } from 'vitest'
import {
  BACKUP_EXTENSION,
  BACKUP_META_EXTENSION,
  GENERATED_CONFIG_MARKER,
  MAX_BACKUPS,
} from '../types'

describe('Neovim Types', () => {
  it('exports correct constants', () => {
    expect(GENERATED_CONFIG_MARKER).toBe('-- Generated by vinela')
    expect(MAX_BACKUPS).toBe(5)
    expect(BACKUP_EXTENSION).toBe('.bak')
    expect(BACKUP_META_EXTENSION).toBe('.meta.json')
  })
})
