// src/features/lua-generator/generators/nodes/trigger/on-startup.ts
// OnStartup trigger node generator

import { LuaBuilder } from '@/features/lua-generator/utils/lua-builder'
import type { GraphNode, TriggerNodeData } from '@/shared/types'
import type {
  CompilationUnit,
  GenerationContext,
  NodeGenerator,
} from '../types'
import { createEmptyUnit } from '../types'

/**
 * OnStartup trigger node generator.
 *
 * OnStartup nodes don't generate any code themselves - they simply
 * mark the entry point for execution. The actual execution flow
 * is generated by traversing from the 'exec' output port.
 *
 * This generator returns an empty unit. The graph traversal engine
 * (Domain 2) handles emitting the downstream code.
 */
export const onStartupGenerator: NodeGenerator<TriggerNodeData> = {
  generate(
    node: GraphNode<TriggerNodeData>,
    context: GenerationContext,
  ): CompilationUnit {
    // OnStartup just marks the entry point - no code generation needed
    // The traversal engine will render the exec branch.
    // Port name is 'exec' (matches the trigger's outgoing exec port in the graph model).
    const execCode = context.renderExecFromPort(node.id, 'exec')

    if (execCode.length === 0) {
      // Empty startup chain - emit diagnostic
      context.emitDiagnostic({
        id: 'trigger-empty-exec',
        severity: 'warning',
        category: 'connectivity',
        message: 'On Startup trigger has no connected execution flow',
        details: `The On Startup node '${node.id}' has no downstream nodes connected to its execution output. No code will be generated for this startup path.`,
        source: {
          graphId: context.graphId,
          nodeId: node.id,
          nodeType: 'trigger',
        },
        suggestions: [
          'Connect action nodes to the On Startup execution output',
          'Remove unused On Startup nodes',
        ],
      })

      return createEmptyUnit(node.id, 'trigger', context.indentLevel)
    }

    // Build the startup block with do...end for scope isolation
    const builder = new LuaBuilder()

    // Apply current indent level
    for (let i = 0; i < context.indentLevel; i++) {
      builder.indent()
    }

    // Create scope isolation block
    builder.block(
      'do',
      (inner) => {
        for (const line of execCode) {
          inner.line(line)
        }
      },
      'end',
    )

    return {
      nodeId: node.id,
      nodeType: 'trigger',
      code: builder
        .build()
        .split('\n')
        .filter((line) => line.length > 0),
      localVars: [],
      inputBindings: {},
      outputBindings: {},
      indentLevel: context.indentLevel,
    }
  },
}
